markdown: rdiscount
highlighter: pygments
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: Z-Plus：摩崖石刻
host: punkyzhu.github.io
desc: 花开花落 .vs. 云卷云舒

custom:
    category:
        default: 默认
        crazy: 疯狂
        geek: 技术极客
        mac: 苹果专区
        gis: 地理信息系统
        digitalm: 数字媒介
    categories:
      - name:  default
        title: 默认

      - name:  crazy
        title: 疯狂

      - name:  geek
        title: 技术极客

      - name:  mac
        title: 苹果专区

      - name:  gis
        title: 地理信息系统

      - name:  digitalm
        title: 数字媒介


    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: Z-Plus
        email: gbzhu4mse@gmail.com
        disqus: your-disqus-short-name              # Disqus缩略标识
        gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        github: punkyzhu                 # GitHub账号
        gravatar: 1cd8c12591616d8c22aaa624f8c07834  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
